[functions]
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"
  external_node_modules = [
    "puppeteer-extra", 
    "next",
    "chrome-aws-lambda"
  ]

[[plugins]]
    package = "netlify-plugin-chromium"
        [plugins.inputs]
            packageManager = "npm"
            setChromePathInEnv = "false"
            failBuildOnError = "true"